### ISSUE TITLE
SHP: Count down the time before authorities are notified of break-ins.

### ISSUE THREAD

**Issue by georgekouts108** [georgekouts108/soen343_smartHomeSimulator_delivery1#44]
- Frontend part for this is already done in the SHP module.

**Comment by kevinlizh1992** [comment]
Countdown will occur when user sets timer, and break-in sets off motion detector. Currently, to test this functionality, it is sufficient to set the timer to alert. The countdown will be shown in console of IDE (for now). Just comment out the code (inside controller --> setTimeBeforeAlert()) if it is not needed and when anyMdsOn() is actually implemented.

**Comment by kevinlizh1992** [comment]
works now, but error after countdown
